name: Audit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v17
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv

      - name: Run audit
        run: devenv --no-tui tasks run audit:check
